# Generated by Django 2.2.6 on 2019-11-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codechallenge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleimages',
            name='processed',
            field=models.IntegerField(default=0),
        ),
    ]
